
const Home = () => (
    <div>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
        <p>YEAH I KNOW ITS UGLY BUT WE'RE WORKING ON IT</p>
    </div>
)


export default Home;